#!/bin/ksh -p
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright (c) 2007, 2011, Oracle and/or its affiliates. All rights reserved.
#
# Copyright (c) 2013-2020 Peter C. Tribble peter.tribble@gmail.com
#

. /usr/lib/brand/tribblix-common/common.ksh

f_interrupted=$(gettext "Installation cancelled due to interrupt.\n")

m_image=$(gettext       "       Image: Preparing at %s.")
m_smf=$(gettext		" Postinstall: Copying SMF seed repository ...")

m_usage=$(gettext "\n        install [-h]")

m_done=$(gettext      " done.")

trap_cleanup() {
	print "$f_interrupted"
	exit $int_code
}

int_code=$ZONE_SUBPROC_NOTCOMPLETE
trap trap_cleanup INT

ZONENAME=""
ZONEPATH=""

# Setup i18n output
TEXTDOMAIN="SUNW_OST_OSCMD"
export TEXTDOMAIN

while getopts "hR:z:" opt; do
	case $opt in
		h)	fail_usage "";;
		R)	ZONEPATH="$OPTARG" ;;
		z)	ZONENAME="$OPTARG" ;;
		*)	fail_usage "";;
	esac
done
shift $((OPTIND-1))

if [[ -z $ZONEPATH || -z $ZONENAME ]]; then
	print -u2 "Brand error: No zone path or name"
	exit $ZONE_SUBPROC_USAGE
fi

# XXX shared/common script currently uses lower case zonename & zonepath
zonename="$ZONENAME"
zonepath="$ZONEPATH"

is_brand_labeled
brand_labeled=$?

ZONEROOT=$ZONEPATH/root

#
# Before installing the zone, set up ZFS dataset hierarchy for the zone root
# dataset.
#
create_active_ds

printf "$m_image\n" $ZONEROOT

#
# as we parse the contents file, make sure it gets flushed
#
/usr/bin/pkgadm sync

#
# this is where we do all the work
#  create mountpoints for loopback mounts
#  clone other files from global zone
#
# fortunately the contents file is sorted so that directories always come
# before the files they contain, just like cpio wants
#
cd /
grep '^/etc' /var/sadm/install/contents | nawk '{print $1}' | sed -e 's:=: :' -e 's:/::' | nawk '{print $1}' | cpio -pdm $ZONEROOT
grep '^/var' /var/sadm/install/contents | nawk '{print $1}' | sed 's:=: :' | nawk '{print $1}' | cpio -pdm $ZONEROOT
find var/sadm/pkg var/sadm/overlays -print -depth | grep -v save/pspool | cpio -pdm $ZONEROOT
mkdir -p $ZONEROOT/opt $ZONEROOT/usr $ZONEROOT/lib
mkdir -p $ZONEROOT/mnt $ZONEROOT/sbin $ZONEROOT/export
mkdir -m 777 $ZONEROOT/tmp
mkdir -m 700 $ZONEROOT/root
ln -s ./usr/bin $ZONEROOT/bin

#
# use the saved pspool files, if we have them
# FIXME fix up the timestamps
# (the ownership and permissions should be correct from the original cpio)
#
find /var/sadm/pkg -xdev -type f | grep '.*/pspool/.*/reloc/etc' | nawk -v DEST=$ZONEROOT '{s=$1; gsub(/.*reloc/,"",s); print "cp "$1, DEST""s }' | sh -s
find /var/sadm/pkg -xdev -type f | grep '.*/pspool/.*/reloc/var' | nawk -v DEST=$ZONEROOT '{s=$1; gsub(/.*reloc/,"",s); print "cp "$1, DEST""s }' | sh -s

#
# copy in a cleaned up contents file
#
egrep -v '^/(boot|kernel|devices|opt|platform)' /var/sadm/install/contents > $ZONEROOT/var/sadm/install/contents

#
# remove metadata for any installed packages that populate /opt
#
for opkg in `grep '^/opt ' /var/sadm/install/contents | cut -d ' ' -f7- | sed s:SUNWcs::` `cat /usr/lib/brand/tribblix-common/pkg.ignorelist`
do
    rm -fr $ZONEROOT/var/sadm/pkg/$opkg
done
	   
#
# This is where the dragons live.
# Unfortunately, /lib contains the SMF manifests (which is an unfortunate place
# for them), so we need to create a sacrificial alternate copy and then delete
# the manifests that aren't valid in a zone
#
# Note that /zonelib/lib must exist beforehand, else zone verification will
# fail, so the path is provided by packaging. We need to populate it here if
# that has not been done already - the first zone creation will trigger
# population.
#
CFGZONELIB=$(LC_ALL=C zonecfg -z $ZONENAME info fs dir=/lib | grep special: | awk '{print $NF}')
ZONELIBTOP=${CFGZONELIB%/*}
ZONELIB="${ZONELIBTOP}/lib"
if [ ! -d ${ZONELIBTOP}/lib/svc ]; then
grep '^/lib' /var/sadm/install/contents | nawk '{print $1}' | sed -e 's:=: :' -e 's:/::' | nawk '{print $1}' | cpio -pdm ${ZONELIBTOP}
#
# remove ignored files
#
for fignore in `cat /usr/lib/brand/tribblix-common/lib.ignorelist`
do
    rm -f ${ZONELIBTOP}/${fignore}
done
fi

#
# and remove any other files that should never exist in a zone
#
for fignore in `cat /usr/lib/brand/tribblix-common/sparse.ignorelist`
do
    rm -f ${ZONEROOT}/${fignore}
done

#
# remove the desktop cache updates that we don't need in a read-only zone
#
rm -fr $ZONEROOT/var/svc/manifest/application/desktop-cache

#
# clean the ignored entries from the contents file
#
TBFILE=/tmp/il.${ZONENAME}.fg.$$
cat /usr/lib/brand/tribblix-common/lib.ignorelist /usr/lib/brand/tribblix-common/sparse.ignorelist > $TBFILE
echo "/var/svc/manifest/application/desktop-cache" >> $TBFILE
mv $ZONEROOT/var/sadm/install/contents $ZONEROOT/var/sadm/install/contents.raw
cat $ZONEROOT/var/sadm/install/contents.raw | fgrep -v -f $TBFILE > $ZONEROOT/var/sadm/install/contents
rm -f $ZONEROOT/var/sadm/install/contents.raw
rm -fr $TBFILE

printf "$m_smf"
PROFILEDIR=etc/svc/profile
rm -f $ZONEROOT/$PROFILEDIR/name_service.xml
rm -f $ZONEROOT/$PROFILEDIR/generic.xml
rm -f $ZONEROOT/$PROFILEDIR/inetd_services.xml
rm -f $ZONEROOT/$PROFILEDIR/platform.xml
ln -s ns_files.xml $ZONEROOT/$PROFILEDIR/name_service.xml
ln -s generic_limited_net.xml $ZONEROOT/$PROFILEDIR/generic.xml
ln -s inetd_generic.xml $ZONEROOT/$PROFILEDIR/inetd_services.xml
ln -s platform_none.xml $ZONEROOT/$PROFILEDIR/platform.xml

# This was formerly done in i.manifest
repfile=$ZONEROOT/etc/svc/repository.db
cp /lib/svc/seed/nonglobal.db $repfile
chmod 0600 $repfile
chown root:sys $repfile

printf "$m_done\n"

# ensure zap catalogs are present
cp -p /etc/zap/repositories/*.catalog $ZONEROOT/etc/zap/repositories
cp -p /etc/zap/repositories/*.aliases $ZONEROOT/etc/zap/repositories
cp -p /etc/zap/repositories/*.overlays $ZONEROOT/etc/zap/repositories

# Clean up root as a role and jack if needed
cat $ZONEROOT/etc/user_attr | /usr/bin/sed '/^root/s:;type=role::' > $ZONEROOT/etc/user_attr.n
mv $ZONEROOT/etc/user_attr.n $ZONEROOT/etc/user_attr
print "/^jack:/d\nw" | ed -s $ZONEROOT/etc/user_attr
print "/^jack:/d\nw" | ed -s $ZONEROOT/etc/passwd
chmod u+w $ZONEROOT/etc/shadow
print "/^jack:/d\nw" | ed -s $ZONEROOT/etc/shadow
chmod u-w $ZONEROOT/etc/shadow

printf "$m_complete\n\n" ${SECONDS}
if (( $brand_labeled == 0 )); then
	printf "$m_postnote\n"
	printf "$m_postnote2\n"
else
	# Umount the dataset on the root.
	umount $ZONEROOT || printf "$f_zfs_unmount" "$ZONEPATH/root"
fi

exit $ZONE_SUBPROC_OK
