.TH "SPARSE-ROOT" "5" "Jun 4, 2017" "Tribblix"
.SH "NAME"
sparse-root zone variant
.SH DESCRIPTION
.LP
The sparse-root zone brand in Tribblix is similar, but not identical,
to the sparse-root zones in Solaris 10.
.LP
The /usr, /sbin, /platform, and /lib file system hierarchies are lofs
mounts from a parent system. By default, the parent system is the
global zone. Unlike Solaris 10, an alternative parent, called a zone
template, can be created and used.
.LP
The recommended way to create zones in Tribblix is to use the
zone-create subcommand of the \fBzap\fR(1) utility.
.LP
For a sparse-root zone, specify -t sparse as follows.
.sp
.in +2
.nf
\fBzap create-zone -t sparse ...\fR
.fi
.in -2
.sp
.SH SEE ALSO
.LP
\fBzones\fR(5), \fBbrands\fR(5), \fBwhole-root\fR(5), \fBzap\fR(1)
