#!/bin/sh
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2024 Peter Tribble
#

#
# unpack an mvi (or similar) tarball into a zone root directory
#
# usage: -d destination tarball
#

usage() {
	echo "Usage: $0 -d destination tarball"
	exit 2
}

bail() {
    echo "ERROR: $1"
    exit 1
}

case $1 in
-d)
	shift
	DESTDIR=$1
	shift
	;;
*)
	usage
	;;
esac

case $# in
1)
	ISOFILE=$1
	;;
*)
	usage
	;;
esac

if [ -z "$DESTDIR" ]; then
   usage
fi
if [ -z "$ISOFILE" ]; then
   usage
fi

#
# check files exist
#
if [ ! -r "$ISOFILE" ]; then
   bail "missing input tarball"
fi
case $DESTDIR in
/*)
if [ ! -d "$DESTDIR" ]; then
   bail "destination does not exist"
fi
;;
*)
bail "destination must be an absolute path"
;;
esac

#
# the destination must exist, and it must be empty
#
NF=$(/bin/ls -1A "$DESTDIR")
if [ -n "$NF" ]; then
   bail "destination must be empty"
fi

#
# and just unpack the tarball
# use gtar to ensure absolute paths and anything with .. get dropped,
# so we can't unpack the file outside the zone root
#
cd "$DESTDIR" || bail "internal cd error"
/usr/bin/gtar xf "$ISOFILE"
