.TH "SPARSE-ROOT" "7" "December 21, 2025" "Tribblix"
.SH "NAME"
sparse-root zone variant
.SH DESCRIPTION
The sparse-root zone brand in Tribblix is similar to, but not identical
to, the sparse-root zones in Solaris 10.
.LP
The /usr, /sbin, and /lib file system hierarchies are lofs
mounts from a parent system. By default, the parent system is the
global zone. Unlike Solaris 10, an alternative parent, called a zone
template, can be created and used.
.LP
The recommended way to create zones in Tribblix is to use the
create-zone subcommand of the \fBzap\fR(1) utility.
.LP
For a sparse-root zone, specify -t sparse as follows.
.sp
.in +2
.nf
\fBzap create-zone -t sparse ...\fR
.fi
.in -2
.sp
.SH SEE ALSO
.BR zap (1),
.BR brands (7),
.BR whole-root (7),
.BR zones (7)
